force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guildies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission_Assignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>Mission_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/tests/SuperheroMissionTriggerTest.cls
@IsTest
private class SuperheroMissionTriggerTest {
    @TestSetup
    static void testSetup() {
        TestDataFactory.createData();
    }

    @IsTest
    static void createPublicMission(){
        delete [SELECT Id FROM Superhero_Mission__c];
        Guild__c guild = [SELECT Id FROM Guild__c LIMIT 1];

        Test.startTest();
            insert TestDataFactory.createMission(1,true,guild.Id, 'A');
        Test.stopTest();

        Superhero_Mission__c mission = [SELECT Id FROM Superhero_Mission__c];
        Assert.isNotNull(mission);
        Assert.isTrue(Limits.getEmailInvocations() == 0);
        for(AsyncApexJob job : [SELECT Id, MethodName, Status FROM AsyncApexJob]) {
            Assert.areEqual(job.Status, 'Completed');
        }
    }

    @IsTest
    static void createSpecialMission(){
        delete [SELECT Id FROM Superhero_Mission__c];
        Contact con = [SELECT Id, LastName FROM Contact LIMIT 1];
        Guild__c guild = [SELECT Id FROM Guild__c LIMIT 1];
        delete [SELECT Id FROM Mission_Assignment__c];
        delete [SELECT Id FROM Hero__c WHERE Guild__c = :guild.Id];

        insert TestDataFactory.createHero(new List<Contact>{con}, 'A',new List<Guild__c>{guild});

        Test.startTest();
            insert TestDataFactory.createMission(1,false,guild.Id, 'B');
        Test.stopTest();

        Superhero_Mission__c mission = [SELECT Id FROM Superhero_Mission__c];
        Assert.isNotNull(mission);
        Assert.isTrue(Limits.getEmailInvocations() == 0);
        for(AsyncApexJob job : [SELECT Id, MethodName, Status FROM AsyncApexJob]) {
            Assert.areEqual(job.Status, 'Completed');
        }
    }
}