force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guildies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;In Progress&apos;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/tests/EmailMissionBatchTest.cls
@IsTest
private class EmailMissionBatchTest {
    @TestSetup
    static void testSetup() {
        TestDataFactory.createData();
        User customerUser = TestDataFactory.createCommunityUser();
        insert customerUser;
    }

    @IsTest
    static void newPublicMissionPositiveTest() {
        User customerUser = [SELECT Id FROM User WHERE Profile.UserLicense.Name = 'Customer Community' LIMIT 1];
        Test.startTest();
        System.runAs(customerUser) {
            Database.executeBatch(new EmailMissionBatch(
                    'NEW_PUBLIC_MISSION', new Set<Superhero_Mission__c>([SELECT Id FROM Superhero_Mission__c LIMIT 1])
            ), 1
            );
        }
        Test.stopTest();
        Assert.isTrue(Limits.getEmailInvocations() == 0);
        for(AsyncApexJob job : [SELECT Id, MethodName, Status FROM AsyncApexJob]) {
            Assert.areEqual(job.Status, 'Completed');
        }
    }

    @IsTest
    static void newSpecialMissionPositiveTest() {
        User customerUser = [SELECT Id FROM User WHERE Profile.UserLicense.Name = 'Customer Community' LIMIT 1];
        Test.startTest();
        System.runAs(customerUser) {
            Database.executeBatch(new EmailMissionBatch(
                    'NEW_SPECIAL_MISSION', new Set<Superhero_Mission__c>([SELECT Id, Guild__c FROM Superhero_Mission__c LIMIT 1])
            ), 1
            );
        }
        Test.stopTest();
        Assert.isTrue(Limits.getEmailInvocations() == 0);
        for(AsyncApexJob job : [SELECT Id, MethodName, Status FROM AsyncApexJob]) {
            Assert.areEqual(job.Status, 'Completed');
        }
    }

    @IsTest
    static void completeMissionPositiveTest() {
        User customerUser = [SELECT Id FROM User WHERE Profile.UserLicense.Name = 'Customer Community' LIMIT 1];
        Test.startTest();
        System.runAs(customerUser) {
            Database.executeBatch(new EmailMissionBatch(
                    'COMPLETED_THE_MISSION', new Set<Mission_Assignment__c>([SELECT Id, Mission__c FROM Mission_Assignment__c LIMIT 1])
            ), 1
            );
        }
        Test.stopTest();
        Assert.isTrue(Limits.getEmailInvocations() == 0);
        for(AsyncApexJob job : [SELECT Id, MethodName, Status FROM AsyncApexJob]) {
            Assert.areEqual(job.Status, 'Completed');
        }
    }

    @IsTest
    static void failedMissionPositiveTest() {
        User customerUser = [SELECT Id FROM User WHERE Profile.UserLicense.Name = 'Customer Community' LIMIT 1];
        delete [SELECT Id FROM Mission_Assignment__c WHERE Status__c = 'Failed'];
        Test.startTest();
        System.runAs(customerUser) {
            Database.executeBatch(new EmailMissionBatch(
                    'FAILED_THE_MISSION', new Set<Mission_Assignment__c>([SELECT Id, Mission__c FROM Mission_Assignment__c LIMIT 1])
            ), 1
            );
        }
        Test.stopTest();
        List<Mission_Assignment__c> failedMissions = [SELECT Id FROM Mission_Assignment__c WHERE Status__c = 'Failed'];
        Assert.isTrue(Limits.getEmailInvocations() == 0);
        Assert.isTrue(failedMissions.size() == 1);
        for(AsyncApexJob job : [SELECT Id, MethodName, Status FROM AsyncApexJob]) {
            Assert.areEqual(job.Status, 'Completed');
        }
    }
}